/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/test2Animations.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model2Animations(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/public/test2Animations.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions.lookAround)
    actions.lookAround.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="TypingArmature" visible={false} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Brazo">
            <skinnedMesh name="Brazomesh" geometry={nodes.Brazomesh.geometry} material={materials.blinn3SGmat} skeleton={nodes.Brazomesh.skeleton} />
            <skinnedMesh name="Brazomesh_1" geometry={nodes.Brazomesh_1.geometry} material={materials.lambert3SGmat} skeleton={nodes.Brazomesh_1.skeleton} />
          </group>
          <group name="Brazo1">
            <skinnedMesh name="Brazo1mesh" geometry={nodes.Brazo1mesh.geometry} material={materials.blinn2SGmat} skeleton={nodes.Brazo1mesh.skeleton} />
            <skinnedMesh name="Brazo1mesh_1" geometry={nodes.Brazo1mesh_1.geometry} material={materials.blinn3SGmat} skeleton={nodes.Brazo1mesh_1.skeleton} />
            <skinnedMesh name="Brazo1mesh_2" geometry={nodes.Brazo1mesh_2.geometry} material={materials.lambert3SGmat} skeleton={nodes.Brazo1mesh_2.skeleton} />
          </group>
          <group name="Cabeza">
            <skinnedMesh name="Cabezamesh" geometry={nodes.Cabezamesh.geometry} material={materials.blinn3SGmat} skeleton={nodes.Cabezamesh.skeleton} />
            <skinnedMesh name="Cabezamesh_1" geometry={nodes.Cabezamesh_1.geometry} material={materials.lambert2SGmat} skeleton={nodes.Cabezamesh_1.skeleton} />
          </group>
          <group name="Cuello">
            <skinnedMesh name="Cuellomesh" geometry={nodes.Cuellomesh.geometry} material={materials.initialShadingGroupmat} skeleton={nodes.Cuellomesh.skeleton} />
            <skinnedMesh name="Cuellomesh_1" geometry={nodes.Cuellomesh_1.geometry} material={materials.lambert3SGmat} skeleton={nodes.Cuellomesh_1.skeleton} />
          </group>
          <group name="Cuerpo">
            <skinnedMesh name="Cuerpomesh" geometry={nodes.Cuerpomesh.geometry} material={materials.blinn2SGmat} skeleton={nodes.Cuerpomesh.skeleton} />
            <skinnedMesh name="Cuerpomesh_1" geometry={nodes.Cuerpomesh_1.geometry} material={materials.lambert3SGmat} skeleton={nodes.Cuerpomesh_1.skeleton} />
          </group>
          <skinnedMesh name="Dedos1" geometry={nodes.Dedos1.geometry} material={materials.blinn3SGmat} skeleton={nodes.Dedos1.skeleton} />
          <skinnedMesh name="Dedos_Fin" geometry={nodes.Dedos_Fin.geometry} material={materials.blinn3SGmat} skeleton={nodes.Dedos_Fin.skeleton} />
          <skinnedMesh name="Mascara" geometry={nodes.Mascara.geometry} material={materials.initialShadingGroupmat} skeleton={nodes.Mascara.skeleton} />
          <skinnedMesh name="pCube3" geometry={nodes.pCube3.geometry} material={materials.blinn2SGmat} skeleton={nodes.pCube3.skeleton} />
          <skinnedMesh name="pCube6" geometry={nodes.pCube6.geometry} material={materials.blinn3SGmat} skeleton={nodes.pCube6.skeleton} />
          <skinnedMesh name="pCube7" geometry={nodes.pCube7.geometry} material={materials.blinn3SGmat} skeleton={nodes.pCube7.skeleton} />
          <skinnedMesh name="pCylinder6" geometry={nodes.pCylinder6.geometry} material={materials.blinn2SGmat} skeleton={nodes.pCylinder6.skeleton} />
          <skinnedMesh name="pCylinder9" geometry={nodes.pCylinder9.geometry} material={materials.blinn3SGmat} skeleton={nodes.pCylinder9.skeleton} />
          <group name="Pierna">
            <skinnedMesh name="Piernamesh" geometry={nodes.Piernamesh.geometry} material={materials.blinn2SGmat} skeleton={nodes.Piernamesh.skeleton} />
            <skinnedMesh name="Piernamesh_1" geometry={nodes.Piernamesh_1.geometry} material={materials.blinn3SGmat} skeleton={nodes.Piernamesh_1.skeleton} />
            <skinnedMesh name="Piernamesh_2" geometry={nodes.Piernamesh_2.geometry} material={materials.lambert3SGmat} skeleton={nodes.Piernamesh_2.skeleton} />
          </group>
          <group name="Pierna1">
            <skinnedMesh name="Pierna1mesh" geometry={nodes.Pierna1mesh.geometry} material={materials.blinn2SGmat} skeleton={nodes.Pierna1mesh.skeleton} />
            <skinnedMesh name="Pierna1mesh_1" geometry={nodes.Pierna1mesh_1.geometry} material={materials.blinn3SGmat} skeleton={nodes.Pierna1mesh_1.skeleton} />
            <skinnedMesh name="Pierna1mesh_2" geometry={nodes.Pierna1mesh_2.geometry} material={materials.lambert3SGmat} skeleton={nodes.Pierna1mesh_2.skeleton} />
          </group>
          <skinnedMesh name="polySurface3" geometry={nodes.polySurface3.geometry} material={materials.blinn2SGmat} skeleton={nodes.polySurface3.skeleton} />
        </group>
        <group name="LookAroundArmature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_1} />
          <group name="Brazo001">
            <skinnedMesh name="Brazomesh001" geometry={nodes.Brazomesh001.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.Brazomesh001.skeleton} />
            <skinnedMesh name="Brazomesh001_1" geometry={nodes.Brazomesh001_1.geometry} material={materials['lambert3SGmat.001']} skeleton={nodes.Brazomesh001_1.skeleton} />
          </group>
          <group name="Brazo1001">
            <skinnedMesh name="Brazo1mesh001" geometry={nodes.Brazo1mesh001.geometry} material={materials['blinn2SGmat.001']} skeleton={nodes.Brazo1mesh001.skeleton} />
            <skinnedMesh name="Brazo1mesh001_1" geometry={nodes.Brazo1mesh001_1.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.Brazo1mesh001_1.skeleton} />
            <skinnedMesh name="Brazo1mesh001_2" geometry={nodes.Brazo1mesh001_2.geometry} material={materials['lambert3SGmat.001']} skeleton={nodes.Brazo1mesh001_2.skeleton} />
          </group>
          <group name="Cabeza001">
            <skinnedMesh name="Cabezamesh001" geometry={nodes.Cabezamesh001.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.Cabezamesh001.skeleton} />
            <skinnedMesh name="Cabezamesh001_1" geometry={nodes.Cabezamesh001_1.geometry} material={materials['lambert2SGmat.001']} skeleton={nodes.Cabezamesh001_1.skeleton} />
          </group>
          <group name="Cuello001">
            <skinnedMesh name="Cuellomesh001" geometry={nodes.Cuellomesh001.geometry} material={materials['initialShadingGroupmat.001']} skeleton={nodes.Cuellomesh001.skeleton} />
            <skinnedMesh name="Cuellomesh001_1" geometry={nodes.Cuellomesh001_1.geometry} material={materials['lambert3SGmat.001']} skeleton={nodes.Cuellomesh001_1.skeleton} />
          </group>
          <group name="Cuerpo001">
            <skinnedMesh name="Cuerpomesh001" geometry={nodes.Cuerpomesh001.geometry} material={materials['blinn2SGmat.001']} skeleton={nodes.Cuerpomesh001.skeleton} />
            <skinnedMesh name="Cuerpomesh001_1" geometry={nodes.Cuerpomesh001_1.geometry} material={materials['lambert3SGmat.001']} skeleton={nodes.Cuerpomesh001_1.skeleton} />
          </group>
          <skinnedMesh name="Dedos1001" geometry={nodes.Dedos1001.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.Dedos1001.skeleton} />
          <skinnedMesh name="Dedos_Fin001" geometry={nodes.Dedos_Fin001.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.Dedos_Fin001.skeleton} />
          <skinnedMesh name="Mascara001" geometry={nodes.Mascara001.geometry} material={materials['initialShadingGroupmat.001']} skeleton={nodes.Mascara001.skeleton} />
          <skinnedMesh name="pCube3001" geometry={nodes.pCube3001.geometry} material={materials['blinn2SGmat.001']} skeleton={nodes.pCube3001.skeleton} />
          <skinnedMesh name="pCube6001" geometry={nodes.pCube6001.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.pCube6001.skeleton} />
          <skinnedMesh name="pCube7001" geometry={nodes.pCube7001.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.pCube7001.skeleton} />
          <skinnedMesh name="pCylinder6001" geometry={nodes.pCylinder6001.geometry} material={materials['blinn2SGmat.001']} skeleton={nodes.pCylinder6001.skeleton} />
          <skinnedMesh name="pCylinder9001" geometry={nodes.pCylinder9001.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.pCylinder9001.skeleton} />
          <group name="Pierna001">
            <skinnedMesh name="Piernamesh001" geometry={nodes.Piernamesh001.geometry} material={materials['blinn2SGmat.001']} skeleton={nodes.Piernamesh001.skeleton} />
            <skinnedMesh name="Piernamesh001_1" geometry={nodes.Piernamesh001_1.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.Piernamesh001_1.skeleton} />
            <skinnedMesh name="Piernamesh001_2" geometry={nodes.Piernamesh001_2.geometry} material={materials['lambert3SGmat.001']} skeleton={nodes.Piernamesh001_2.skeleton} />
          </group>
          <group name="Pierna1001">
            <skinnedMesh name="Pierna1mesh001" geometry={nodes.Pierna1mesh001.geometry} material={materials['blinn2SGmat.001']} skeleton={nodes.Pierna1mesh001.skeleton} />
            <skinnedMesh name="Pierna1mesh001_1" geometry={nodes.Pierna1mesh001_1.geometry} material={materials['blinn3SGmat.001']} skeleton={nodes.Pierna1mesh001_1.skeleton} />
            <skinnedMesh name="Pierna1mesh001_2" geometry={nodes.Pierna1mesh001_2.geometry} material={materials['lambert3SGmat.001']} skeleton={nodes.Pierna1mesh001_2.skeleton} />
          </group>
          <skinnedMesh name="polySurface3001" geometry={nodes.polySurface3001.geometry} material={materials['blinn2SGmat.001']} skeleton={nodes.polySurface3001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/public/test2Animations.glb')
